{% set name = "cccl-python" %}
{% set version = "1.2.1" %}
{% set cuda_major_version = environ.get("cuda_compiler_version", "12.9").split(".")[0] | int %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/NVIDIA/cccl/archive/refs/tags/python-{{ version }}.tar.gz
  sha256: 2312aac9473ffc0a57e07090719c18a7ab3e0b624b66948841c3552b706a29ce
  patches:
    - 0001-Include-memory-in-for_op_helper.h.patch

build:
  number: 0
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script:
    # We only need cc=75 because of the CCCL C library's design.
    - export CMAKE_GENERATOR=Ninja  # [linux]
    - export CUDAARCHS=75  # [linux]
    - set "CMAKE_GENERATOR=Ninja"  # [win]
    - set "CMAKE_GENERATOR_TOOLSET="   # [win]
    - set "CMAKE_GENERATOR_PLATFORM="  # [win]
    - set "CUDA_PATH=%PREFIX%\Library"  # [win]
    - set "CUDAARCHS=75"  # [win]
    - {{ PYTHON }} -m pip install python/cuda_cccl -vv --no-deps --no-build-isolation
  string: cuda{{ cuda_major_version }}_py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}
  skip: true  # [osx or py<310]
  ignore_run_exports_from:
    - {{ compiler('cuda') }}
    - cuda-nvrtc-dev
    - libnvjitlink-dev
    - cuda-driver-dev  # [linux]
  missing_dso_whitelist:
    # Needed DSO by 'libcccl.c.parallel.so'
    - "*/libcuda.so.1"  # [linux]
    # this is dynamically loaded at run time
    - "*/cccl.c.parallel.dll"  # [win]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}
    - cmake >=3.30
    - ninja-base
  host:
    - python
    - pip
    - setuptools-scm
    - cython >=3.1.0
    - scikit-build-core >=0.10
    - cuda-version {{ cuda_compiler_version }}
    - cuda-nvrtc-dev
    - libnvjitlink-dev
    - cuda-driver-dev  # [linux]
  run:
    - python
    - numpy
    - cuda-pathfinder >=1.2.3,<2.0.0a0
    - cuda-core
    - cuda-cudart
    - typing-extensions
    - {{ pin_compatible("cuda-version", min_pin="x") }}
    - {{ pin_compatible('cuda-nvrtc', min_pin='x', max_pin='x') }}
    - {{ pin_compatible('libnvjitlink', min_pin='x', max_pin='x') }}
  run_constrained:
    # We need a GPU to run cccl-python
    - __cuda >=12.0
    # Optional JIT backend for Python callables
    - numba-cuda-mlir >=0.5.2,<0.6

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - cuda.compute
    - cuda.cccl.headers

about:
  home: https://github.com/NVIDIA/cccl
  summary: 'Python interfaces to CUDA Core Compute Libraries (CCCL)'
  description: 'Python interfaces to CUDA Core Compute Libraries (CCCL)'
  license: LicenseRef-NVIDIA-SOFTWARE-LICENSE
  license_file: LICENSE
  license_family: Other
  doc_url: https://nvidia.github.io/cccl/unstable/python
  dev_url: https://github.com/NVIDIA/cccl

extra:
  recipe-maintainers:
    - conda-forge/cuda-python
    - leofang
    - cpcloud
    - oleksandr-pavlyk
    - shwina
